//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kennels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KennelsModelContainer : DbContext
    {
        public KennelsModelContainer()
            : base("name=KennelsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<Pen> Pens { get; set; }
        public virtual DbSet<Kennel> Kennels { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<DogBreed> DogBreeds { get; set; }
        public virtual DbSet<BirdSpecies> BirdSpecies { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
